{{- if and (.Capabilities.APIVersions.Has "networking.istio.io/v1") .Values.ingress.enabled }}
{{- $fullName := include "fabrik8.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "fabrik8.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  hosts:
  {{- range $host := .Values.ingress.hosts }}
  - {{ tpl $host.host $ | quote }}
  {{- end }}
  gateways:
  - istio-system/gateway
  http:
    {{- range $host := .Values.ingress.hosts }}
    - route:
      - destination:
          host: {{ $fullName }}
          port:
            number: {{ $svcPort }}
    {{- end }}
{{- end }}